name: Deploy to Azure Web App

on:
  push:
    branches:
      - streamlit-consume  # Ensure this matches your pushed branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Ensure your Python version is correct

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r "Streamlit app/requirements.txt"  # Correct path

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: cxqa-streamlit-webapp
        slot-name: production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISH_PROFILE }}
