name: Deploy to Azure Web App

on:
  push:
    branches:
      - streamlit-consume  # Specify your branch here

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub Actions token for authentication

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Ensure this secret contains the correct JSON credentials

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Azure Web App
        run: |
          az webapp up --name cxqa-streamlit-webapp --resource-group cxqa-rg2 --sku F1
